### PR TITLE
United headers for columns

### PR DESCRIPTION
**Pull request by Cassage**
This prop (actually, I'm not sure if it should be inside state props but I couldn't really get how to put it somewhere else) is created in order to render 1 header for all columns (of course, priority of such header is less than specified in columns array), I have met case where it really helps so I decided to create something like that.

### CODE REVIEW

**Comment by KevinVandy** [comment]
I don't get what this accomplishes

**Comment by Cassage** [comment]
> I don't get what this accomplishes

It helps write less code if all columns have same header. In my case I have over 100 headers in 1 table and creating over 100 absolutely similar similar headers looks like a very weird idea when I can make such move with 1 props

**Comment by KevinVandy** [comment]
There is already a defaultColumn prop/ table option that does this

**Comment by KevinVandy** [comment]
@Cassage  So just do this in your code instead, as it is already supported exactly for this situation.

```tsx
<MaterialReactTable
  columns={columns}
  data={data}
  defaultColumn={{
    header: defaultHeader,
  }}
/>
```

**Comment by Cassage** [comment]
> @Cassage So just do this in your code instead, as it is already supported exactly for this situation.
> 
> ```tsx
> <MaterialReactTable
>   columns={columns}
>   data={data}
>   defaultColumn={{
>     header: defaultHeader,
>   }}
> />
>

Thanks, didn't know about such feature

**Pull request closed without merging**
