### PR TITLE
Show ellipsis when header cell overflows

### PR DESCRIPTION
**Pull request by tacigar**
Hi!
Currently if the header overflows when the column is resized, it will look like the this:

スクリーンショット 2022-09-20 16 49 17

This is a little hard to see, so how about showing the ellipsis instead?

https://user-images.githubusercontent.com/19551419/191196293-0acd9b3f-f1d5-4c32-aa88-50224f800bfb.mov

### CODE REVIEW

**Review by KevinVandy — CHANGES_REQUESTED** [review]
I think this is a good idea, but the code could be a lot simpler and accomplish the same thing. No need to manage open state. I'll experiment with this. I'd prefer not to add any more Box elements.

**Comment by tacigar** [comment]
@KevinVandy 
The current implementation is to display the full name in Tooltip only when ellipsis is visible.
And the check if ellipsis is displayed is done in Tooltip's onOpen prop.
This is to minimize the calculation of whether ellipsis is visible or not.
And since I used `onOpen` prop, the Tooltip became "Controlled" and thus I needed to use state to control whether the Tooltip is open or not.

Controlling ellipsis is quite difficult and I could not think of a way to do it other than adding a Box component..

**Comment by KevinVandy** [comment]
> @KevinVandy The current implementation is to display the full name in Tooltip only when ellipsis is visible. And the check if ellipsis is displayed is done in Tooltip's `onOpen` prop. This is to minimize the calculation of whether ellipsis is visible or not. And since I used `onOpen` prop, the Tooltip became "Controlled" and thus I needed to add a state to control whether the Tooltip is open or not.
> 
> And.. controlling ellipsis is quite difficult and I could not think of a way to do it other than adding a Box component.. Also I think something that wraps `header` is also needed to calculate if ellipsis is displayed.

I do want to probably end up merging something like this, though may change a few things to work better with some automatic wrapping that some have requested. Right now this PR has merge conflicts though

**Comment by tacigar** [comment]
I got it 🙇 
I resolved conflicts.

**Review by KevinVandy — APPROVED** [review]

**Pull request merged**
