### PR TITLE
Managing skeleton for rows v2

### PR DESCRIPTION
**Pull request by Cassage**

### CODE REVIEW

**Comment by Cassage** [comment]
The way we made it wasn't really working for me (cell.getValue() might be undefined, or, for example, be null intentionally and loading skeleton for it doesn't sound like a good idea), so I came up with another idea - creating props so we can manage it properly.

**Comment by Cassage** [comment]
Hello, what was wrong with my PR for you to close it without any comment? I'm willing to improve it in order to make it merged since this feature is quite important for my project @KevinVandy

**Comment by KevinVandy** [comment]
I thought I had established that it will now be possible to do this without any new props. This is very much an edge case feature that only a handful of people would ever use. So if it can be implemented already, let's now add even more props.

I have not deployed a material example yet, but here is the mantine one https://www.mantine-react-table.dev/?path=/story/features-loading-examples--loading-with-some-data

**Comment by Cassage** [comment]
> I thought I had established that it will now be possible to do this without any new props. This is very much an edge case feature that only a handful of people would ever use. So if it can be implemented already, let's now add even more props.
> 
> I have not deployed a material example yet, but here is the mantine one https://www.mantine-react-table.dev/?path=/story/features-loading-examples--loading-with-some-data

Oh, okay, It just that I wasn't really satisfied with previous version of skeleton (here it is -> (isLoading || showSkeletons) && cell.getValue() === null) because it's quite sad to rely on cell.getValue(), if you already have proper solution without such problems - it's nice to hear, will wait till' you deploy

**Comment by AndreyGrek** [comment]
@KevinVandy, `cell.getValue() === undefined` does not work for me either, I would like to manage the skeleton properly, this PR is very simple and works well for me too, you can think about approving it

**Pull request closed without merging**
