### PR TITLE
feat: add no data customization

### PR DESCRIPTION
**Pull request by swyftx-simon**
This quick PR adds the ability to style the the table body when there are no rows.
Happy to adjust the PR as required @KevinVandy 😄

### CODE REVIEW

**Comment by KevinVandy** [comment]
First of all, thanks for looking into adding a feature like this.

However, I try to avoid adding features that can already be accomplished in a different way.

For example I think devs can already do this with `muiTableBodyProps` like so:

```jsx
muiTableBodyProps={({table}) => ({
  children: !table.getRowModel().rows.length ? <CustomNoRowsComponent /> : undefined
})}
```

Wondering if it would be better to document this trick somewhere rather than make a new prop?

**Comment by swyftx-simon** [comment]
Ah that is a neat trick! Yes adding it to the docs/storybook would be great.

**Comment by KevinVandy** [comment]
My suggestion technically wasn't possible, but is now in v1.3.10

**Comment by brunol55** [comment]
It doesn't work on the current version 1.3.15, or am I doing something wrong?

**Pull request closed without merging**
