### PR TITLE
Show / hide all buttons don't set header group visibility state

### PR DESCRIPTION
**Pull request by ThisIsHG**
This PR is related to #1013

### CODE REVIEW

**Comment by KevinVandy** [comment]
I'm actually thinking of reverting all this new logic in MRT. I think that TanStack Table's APIs should handle this.

Though can you tell me what the use case is for seeing whether or not column groups are visible?

**Comment by ThisIsHG** [comment]
@KevinVandy 
We have a table with repeating column groups with the following leaf columns:

|Evaluation|Detail A|Detail B|Detail ...|
|---|---|---|---|

for those where a evaluation is present only the evaluation should be visible by default and for those without the details should be always visible.

We also implemented a detail switch wich shows those columns where a evaluation is present.

But when a column group is hidden as a whole and the detail view is enabled those column groups which should remain hidden appear again because there is no other way of determining if those columns should be set to visible again since we can't rely on the Evaluation column.

**Comment by KevinVandy** [comment]
@ThisIsHG I think I'll just change TanStack Table like this:
image

image

**Comment by KevinVandy** [comment]
@ThisIsHG If v2.12.1 works for you, we can close this PR.

**Comment by ThisIsHG** [comment]
Will validate it first thing in morning tomorrow! But thanks in advance!

**Comment by ThisIsHG** [comment]
@KevinVandy works like a charm!

Thanks for bringing it so fast into the Table!

**Pull request closed without merging**
