### PR TITLE
Update virtualization, bug-fix: dancing rows

### PR DESCRIPTION
**Pull request by AndreyGrek**

### CODE REVIEW

**Comment by KevinVandy** [comment]
I was literally about to do something similar. I'm about to release v1.4 which has support for the new grid/flex layout mode that will make proper virtualization much easier. I'll have to look into how this PR solves it

**Comment by AndreyGrek** [comment]
> > oh, I'm fix bug, but did not have time,
> > what is turborepo?
> 
> Yeah a couple days ago I refactored this project to use PNPM and Turborepo instead of yarn. Moved a bunch of stuff around. I updated the CONTRIBUTING.md with new instructions to run the project locally.

Ok, I'll take a look tomorrow and reopen PR

**Comment by KevinVandy** [comment]
> Everything is ok there and the quality of the code adhered to your style. **But** one nuance that I have not been able to overcome so far - if you scroll the table for a long time, it starts to lag

One of the reasons I was looking to go with the more traditional approach of using `translate` is that it that I think it uses hardware acceleration, so it might solve that. 

So I might be both upgrading to the latest beta of TanStack Virtual, and re-implementing it if possible. We'll see. Otherwise your fixes might be good enough for now.

**Comment by KevinVandy** [comment]
@AndreyGrek This [commit](https://github.com/KevinVandy/material-react-table/commit/00656e09cf7693536d4d18dd0a1f361ac6f50d82) ended up taking some important inspiration from your PR here. But I needed to build upon it al lot more with the css flex/grid layout stuff. Also needed to fix where some of the CSS provided broke all the features when virtualization was turned off.

I'll be sure to credit you in the release notes when v1.4 drops though.

**Comment by AndreyGrek** [comment]
> @AndreyGrek This [commit](https://github.com/KevinVandy/material-react-table/commit/00656e09cf7693536d4d18dd0a1f361ac6f50d82) ended up taking some important inspiration from your PR here. But I needed to build upon it al lot more with the css flex/grid layout stuff. Also needed to fix where some of the CSS provided broke all the features when virtualization was turned off.
> 
> 
> 
> I'll be sure to credit you in the release notes when v1.4 drops though.

Thanks. But I didn't quite understand, doesn't I need to check new source (make new PR)? 

Or have you already moved my edits? :)

**Comment by KevinVandy** [comment]
> > @AndreyGrek
> Thanks. But I didn't quite understand, doesn't I need to check new source (make new PR)? 
> 
> Or have you already moved my edits? :)

I couldn't merge your PR because of merge conflicts, so I just implemented it myself. It is testable on the docs and storybook sites. You should see no more row flicking or jumping bugs

**Comment by AndreyGrek** [comment]
> > > @AndreyGrek
> > Thanks. But I didn't quite understand, doesn't I need to check new source (make new PR)? 
> > 
> > Or have you already moved my edits? :)
> 
> I couldn't merge your PR because of merge conflicts, so I just implemented it myself. It is testable on the docs and storybook sites. You should see no more row flicking or jumping bugs
> 

Kevin, thank you very much. Flicking and jumping bugs didn't give me rest. 

When is the next release of your library expected, so that I can roll in these changes myself?

**Pull request closed without merging**
