### PR TITLE
Single group alt

### PR DESCRIPTION
**Pull request by KevinVandy**

### CODE REVIEW

**Comment by KevinVandy** [comment]
@dangkhoa99 I think I have a much simpler implementation with no new APIs. I wonder if this satisfies your use case

image

**Comment by KevinVandy** [comment]
I have branched off of your PR so that when merged, you still get credit

**Comment by dangkhoa99** [comment]
in my case, i need `addColumnToLeafNode` feature, and display column header according to `addColumnToLeafNode`. Can you add this option? [Link](https://github.com/KevinVandy/material-react-table/pull/915#issuecomment-1879588662)

**Comment by dangkhoa99** [comment]
I think you can set option `addColumnToLeafNode ?: 'last-grouping' | string`, and 'last-grouping' replace to `showOpenedGroup`

**Comment by KevinVandy** [comment]
@dangkhoa99 By `addColumnToLeafNode`, do you mean still showing the column that it is grouped by in the list of columns?

**Comment by KevinVandy** [comment]
@dangkhoa99 Join the discord for more convos maybe if you can/want

**Comment by Menghini** [comment]
Hello, I have already benefited from this feature in my project. However, it would be great to also have the column filters present or the global filter working with this new "remove" feature. I made a post about it at #929 with further information.

**Pull request merged**
