### PR TITLE
Improve Accessibility - captions

### PR DESCRIPTION
**Pull request by lalong13**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

> A caption functions like a heading for a table. Most screen readers announce the content of captions. Captions help users to find a table and understand what it’s about and decide if they want to read it. If the user uses “Tables Mode”, captions are the primary mechanism to identify tables. The caption is provided by the <caption> element.

from: https://www.w3.org/WAI/tutorials/tables/caption-summary/

### CODE REVIEW

**Comment by KevinVandy** [comment]
I'm open to adding a `caption` slot, but more work would be needed here. Nothing was added to the types yet.

**Review by KevinVandy — CHANGES_REQUESTED** [review]
needs types, and maybe it should be `renderCaption`?

**Comment by KevinVandy** [comment]
and we'll need to make a few storybook examples showing how to use this, and what it looks like

**Comment by lalong13** [comment]
Thanks for the quick response. I don't actually use TypeScript tho I think I can read through it well enough. I'm glad you support the idea. I can look into what would need to be added to make this compliant with the rest of the code base.

If it is renderCaption, do you think it makes sense to have just a string? I was thinking of allowing JSX so that the caption could be visible only to screen readers with the addition of some css/style. This would probably be my own use case.

**Comment by KevinVandy** [comment]
I guess it could just be a string in `caption`. I'll check out the branch and add some examples and types

**Comment by KevinVandy** [comment]
Currently still having a problem with the mui Table component where the caption renders at the bottom of the table no matter what `caption-side` is specified, but will merge what's done for now

image

**Review by KevinVandy — APPROVED** [review]

**Comment by KevinVandy** [comment]
nvm fixed it in the examples

**Comment by lalong13** [comment]
Thank you Kevin! I was going to look into making the updates you recommended this morning, but I see you have already fixed everything up. I greatly appreciate the effort!

**Pull request merged**
