### PR TITLE
add zh locale

### PR DESCRIPTION
**Pull request by samchiu90**
zh-Hant: Traditional Chinese
zh-Hans: Simplified Chinese

### CODE REVIEW

**Comment by LvChengbin** [comment]
There a some imprecise words in simplified Chinese locale, are you guys can accept other contributions on it?

**Comment by samchiu90** [comment]
> There a some imprecise words in simplified Chinese locale, are you guys can accept other contributions on it?

I don't mind. Anyway, zh-Hant has been changed by other users already.

Some Chinese words can have different meanings in different places and scenarios,
like `行` and `列`, in some places, it means row while in some other places and it means column.

In my option, horizontal and vertical writing will also change the meanings of `行`.
If the user focuses on the record, the user may call the row `行`.
If the user focuses on the column difference between different records, the user may also call the column `行`.

Although `hk`, `mo`, and `tw` use `zh-Hant`, and `cn`, `my` and `sg` use `zh-Hans`, 
the wordings between those places are different so you may feel the wordings are imprecise.

You can also use [Custom Non-Built-In Translations](https://www.material-react-table.com/docs/guides/localization#custom-non-built-in-translations) to override the default translation, I believe, but you can create your pull request if the words in zh-Hans are really imprecise.

**Comment by KevinVandy** [comment]
> There a some imprecise words in simplified Chinese locale, are you guys can accept other contributions on it?

I don't know any of the languages myself. I just run the PRs through Google translate real quick for review, but I mostly merge anything to do with locales. Happy to fix any inaccurate translations

**Comment by LvChengbin** [comment]
Yes, using `行` instead of `横列`  is a good case which I want to point out, and there are also some other cases that I think it should be modified.
All the meanings of the words are correct, but some of them do not conform the code of simplified Chinese.

**Comment by LvChengbin** [comment]
I don't know the differences codes of simplified Chinese between `cn`, `my` and `sg`.
I will post a changing map before sending a pr, and you can help me to review them.

**Comment by samchiu90** [comment]
@LvChengbin Actually `橫列` is from Apple:

https://support.apple.com/zh-hk/guide/numbers/tan0403655e1/mac
https://support.apple.com/zh-tw/guide/numbers/tan0403655e1/mac
https://support.apple.com/zh-mo/guide/numbers/tan0403655e1/mac

image

Microsoft uses `列` to represent `row` for `zhhk` and `zhtw`, and `行` to represent `row` for `zhcn` and `jajp`

https://support.microsoft.com/zh-HK/office/row-%E5%87%BD%E6%95%B8-3a63b74a-c4d0-4093-b49a-e76eb49a6d8d
https://support.microsoft.com/zh-TW/office/row-%E5%87%BD%E6%95%B8-3a63b74a-c4d0-4093-b49a-e76eb49a6d8d
https://support.microsoft.com/zh-cn/office/row-%E5%87%BD%E6%95%B0-3a63b74a-c4d0-4093-b49a-e76eb49a6d8d
https://support.microsoft.com/ja-jp/office/row-%E9%96%A2%E6%95%B0-3a63b74a-c4d0-4093-b49a-e76eb49a6d8d

image
image

Annoying, right?

I believe that the best way is to use `橫列` for `zh-Hant` and `橫行` for `zh-Hans`.

**Comment by samchiu90** [comment]
@bluelovers @LvChengbin 
Please check the translations in my fork.
https://github.com/KevinVandy/material-react-table/compare/main...samchiu90:material-react-table:2023_03_02_ZH

**Comment by KevinVandy** [comment]
> @bluelovers @LvChengbin 
> Please check the translations in my fork.
> https://github.com/KevinVandy/material-react-table/compare/main...samchiu90:material-react-table:2023_03_02_ZH

In case it wasn't clear, I'd love any corrections to be prd to MRT

**Comment by samchiu90** [comment]
https://github.com/KevinVandy/material-react-table/pull/409
@LvChengbin @bluelovers

**Pull request merged**
